targetSystem: "linux"
datadog:
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true

  site: datadoghq.com
  kubelet:
    tlsVerify: false
  apm:
    socketEnabled: true 
  logs:
    enabled: true
    containerCollectAll: true
  
agents:
  image:
    name: agent
    tagSuffix: "jmx"

  podAnnotations:
    ad.datadoghq.com/agent.checks: |
      {"jmx_self_discovery":{"init_config":{"is_jmx":true,"java_options": "-Djdk.attach.allowAttachSelf=true"},"instances":[{"process_name_regex": ".*org.datadog.jmxfetch.App.*","collect_default_jvm_metrics":true,"max_returned_metrics":300000,"new_gc_metrics":true,"tools_jar_path":"I_am_useless","conf":[{"include":{"domain_regex":"JMXFetch"}}]}]}}
