targetSystem: "linux"
datadog:
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true

  site: datadoghq.com
  kubelet:
    tlsVerify: false
  apm:
    socketEnabled: true 
  logs:
    enabled: true
    containerCollectAll: true
  confd:
    jmxselftracking.yaml: |-
      init_config:
        is_jmx: true
        java_options: "-Djdk.attach.allowAttachSelf=true"
      instances:
        - process_name_regex: .*org.datadog.jmxfetch.App.*
          name: jmx_2_test_self
          collect_default_jvm_metrics: true
          max_returned_metrics: 300000
          new_gc_metrics: true
          conf:
            - include:
                domain_regex: java\.lang.*|JMXFetch
                attribute:
                - TotalPhysicalMemorySize
                - FreePhysicalMemorySize
                - TotalMemorySize
                - FreeMemorySize
                - AttributeCount
                - MetricCount
                - BeanCount
                - Instance
          tools_jar_path: "notimportant"
          tags:
          - jmx:fetch
agents:
  image:
    name: agent
    tagSuffix: "jmx"
